version: "3"

services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_DIR=/srv
    ports:
      - 3000:3000
    links:
      - nginx
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - 80:80
