FROM nginx:latest

ARG CONSUL_TEMPLATE_VERSION="0.18.3"

ENV CONSUL_TEMPLATE_VERSION=${CONSUL_TEMPLATE_VERSION}
ENV NGINX_PORT="80"
ENV CONSUL_URL="consul:8500"

EXPOSE ${NGINX_PORT}

VOLUME /nginx_templates

RUN apt-get update && \
    apt-get install -y \
    curl

COPY nginx_entrypoint.sh entrypoint.sh

COPY nginx_templates/default.ctmpl /nginx_templates

RUN curl https://releases.hashicorp.com/consul-template/0.18.3/consul-template_0.18.3_linux_amd64.tgz | tar -zxC /usr/bin

#ENTRYPOINT [ "bash", "/entrypoint.sh"]
